import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { appendStatus, calculateFare, createAudit, getDashboardStats, getDb, getDriverProfile, getPricingRule, listAdminOrders, listCustomerOrders, listDriverOffers, listDriverTrips, orders, driverOffers, driverProfiles, orderStatusHistory, ratings, users, vehicles } from "./db";
import { and, desc, eq, sql } from "drizzle-orm";
import { orderStatusValues, vehicleTypeValues } from "../drizzle/schema";

const statusLabels: Record<string, string> = { PENDING: "قيد المراجعة", SEARCHING_DRIVER: "جاري البحث عن سائق", DRIVER_ASSIGNED: "تم تعيين السائق", DRIVER_GOING_TO_PICKUP: "السائق في الطريق للاستلام", ARRIVED_AT_PICKUP: "وصل السائق للاستلام", ORDER_PICKED_UP: "تم استلام الشحنة", IN_DELIVERY: "جاري التوصيل", ARRIVED_AT_DESTINATION: "وصل السائق للوجهة", DELIVERED: "تم التسليم", COMPLETED: "مكتمل", CANCELLED: "ملغى", FAILED_DELIVERY: "تعذر التسليم" };
const activeStatuses = ["DRIVER_ASSIGNED", "DRIVER_GOING_TO_PICKUP", "ARRIVED_AT_PICKUP", "ORDER_PICKED_UP", "IN_DELIVERY", "ARRIVED_AT_DESTINATION"] as const;
const transitionMap: Record<string, string[]> = { DRIVER_ASSIGNED: ["DRIVER_GOING_TO_PICKUP", "CANCELLED"], DRIVER_GOING_TO_PICKUP: ["ARRIVED_AT_PICKUP", "CANCELLED"], ARRIVED_AT_PICKUP: ["ORDER_PICKED_UP"], ORDER_PICKED_UP: ["IN_DELIVERY"], IN_DELIVERY: ["ARRIVED_AT_DESTINATION"], ARRIVED_AT_DESTINATION: ["DELIVERED"], DELIVERED: ["COMPLETED"] };
const vehicleEnum = z.enum(vehicleTypeValues);
const addressSchema = z.object({ address: z.string().min(3).max(500), lat: z.number().optional(), lng: z.number().optional() });

function roleOf(user: { role: string }) { return user.role === "user" ? "CUSTOMER" : user.role; }
function requireRole(user: { role: string }, role: "CUSTOMER" | "DRIVER" | "ADMIN") { if (roleOf(user) !== role) throw new TRPCError({ code: "FORBIDDEN", message: "ليس لديك صلاحية لهذا الإجراء" }); }

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
    chooseRole: protectedProcedure.input(z.object({ role: z.enum(["CUSTOMER", "DRIVER"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "قاعدة البيانات غير متاحة" }); await db.update(users).set({ role: input.role }).where(eq(users.id, ctx.user.id)); return { role: input.role }; }),
  }),
  pricing: router({ estimate: publicProcedure.input(z.object({ vehicleType: vehicleEnum, distanceKm: z.number().min(0).max(500), weightKg: z.number().min(0).max(1000) })).query(async ({ input }) => { const rule = await getPricingRule(input.vehicleType); return { ...calculateFare(rule, input.distanceKm, input.weightKg), currency: "EGP", ruleConfigured: Boolean(rule && Number(rule.baseFare) + Number(rule.perKm) > 0) }; }) }),
  customer: router({
    orders: protectedProcedure.query(async ({ ctx }) => { requireRole(ctx.user, "CUSTOMER"); return listCustomerOrders(ctx.user.id); }),
    createOrder: protectedProcedure.input(z.object({ pickup: addressSchema, dropoff: addressSchema, vehicleType: vehicleEnum, packageDescription: z.string().min(3).max(2000), weightKg: z.number().positive().max(1000), distanceKm: z.number().min(0).max(500).default(0) })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, "CUSTOMER"); const db = await getDb(); if (!db) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "قاعدة البيانات غير متاحة" }); const rule = await getPricingRule(input.vehicleType); const estimate = calculateFare(rule, input.distanceKm, input.weightKg); const result = await db.insert(orders).values({ customerId: ctx.user.id, status: "SEARCHING_DRIVER", pickupAddress: input.pickup.address, pickupLat: input.pickup.lat?.toString(), pickupLng: input.pickup.lng?.toString(), dropoffAddress: input.dropoff.address, dropoffLat: input.dropoff.lat?.toString(), dropoffLng: input.dropoff.lng?.toString(), packageDescription: input.packageDescription, weightKg: input.weightKg.toString(), vehicleType: input.vehicleType, estimatedDistanceKm: input.distanceKm.toString(), estimatedFare: estimate.fare.toString(), paymentMethod: "CASH_ON_DELIVERY", paymentStatus: "UNPAID" }); const orderId = Number(result[0].insertId); const expiresAt = new Date(Date.now() + 5 * 60 * 1000); const candidate = (await db.select({ profile: driverProfiles }).from(driverProfiles).innerJoin(vehicles, eq(vehicles.driverId, driverProfiles.id)).where(and(eq(driverProfiles.driverStatus, "ONLINE"), eq(vehicles.vehicleType, input.vehicleType), eq(vehicles.isActive, true))).limit(1))[0]?.profile; if (candidate) { await db.insert(driverOffers).values({ orderId, driverId: candidate.id, status: "PENDING", expiresAt }); await db.update(orders).set({ driverOfferExpiresAt: expiresAt }).where(eq(orders.id, orderId)); } await appendStatus(orderId, null, "SEARCHING_DRIVER", ctx.user.id, candidate ? "تم إنشاء الطلب وإرسال عرض إلى سائق متاح" : "تم إنشاء الطلب وسيتم تصعيده عند عدم توفر سائق"); return { orderId, status: "SEARCHING_DRIVER", statusLabel: statusLabels.SEARCHING_DRIVER, estimatedFare: estimate.fare, currency: "EGP", offerCreated: Boolean(candidate) }; }),
    track: protectedProcedure.input(z.object({ orderId: z.number().int() })).query(async ({ ctx, input }) => { requireRole(ctx.user, "CUSTOMER"); const db = await getDb(); if (!db) return null; const order = (await db.select().from(orders).where(and(eq(orders.id, input.orderId), eq(orders.customerId, ctx.user.id))).limit(1))[0]; if (!order) throw new TRPCError({ code: "NOT_FOUND", message: "الطلب غير موجود" }); const history = await db.select().from(orderStatusHistory).where(eq(orderStatusHistory.orderId, input.orderId)).orderBy(desc(orderStatusHistory.createdAt)); return { order, statusLabel: statusLabels[order.status], history }; }),
    rateDriver: protectedProcedure.input(z.object({ orderId: z.number().int(), score: z.number().int().min(1).max(5), comment: z.string().max(1000).optional() })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, "CUSTOMER"); const db = await getDb(); if (!db) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "قاعدة البيانات غير متاحة" }); const order = (await db.select().from(orders).where(and(eq(orders.id, input.orderId), eq(orders.customerId, ctx.user.id))).limit(1))[0]; if (!order || !order.driverId || !["DELIVERED", "COMPLETED"].includes(order.status)) throw new TRPCError({ code: "BAD_REQUEST", message: "يمكن التقييم بعد اكتمال التسليم فقط" }); const existing = await db.select().from(ratings).where(eq(ratings.orderId, input.orderId)).limit(1); if (existing.length) throw new TRPCError({ code: "CONFLICT", message: "تم تقييم هذا الطلب مسبقاً" }); await db.insert(ratings).values({ orderId: input.orderId, customerId: ctx.user.id, driverId: order.driverId, score: input.score, comment: input.comment }); return { success: true }; }),
  }),
  driver: router({
    profile: protectedProcedure.query(async ({ ctx }) => { requireRole(ctx.user, "DRIVER"); return getDriverProfile(ctx.user.id); }),
    onboard: protectedProcedure.input(z.object({ nationalIdLast4: z.string().length(4), vehicleType: vehicleEnum, make: z.string().max(100).optional(), model: z.string().max(100).optional(), plateNumber: z.string().max(50).optional(), capacityKg: z.number().positive().max(10000) })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, "DRIVER"); const db = await getDb(); if (!db) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "قاعدة البيانات غير متاحة" }); let profile = await getDriverProfile(ctx.user.id); if (!profile) { const created = await db.insert(driverProfiles).values({ userId: ctx.user.id, nationalIdLast4: input.nationalIdLast4 }).$returningId(); profile = (await getDriverProfile(ctx.user.id))!; } else { await db.update(driverProfiles).set({ nationalIdLast4: input.nationalIdLast4 }).where(eq(driverProfiles.id, profile.id)); } await db.insert(vehicles).values({ driverId: profile.id, vehicleType: input.vehicleType, make: input.make, model: input.model, plateNumber: input.plateNumber, capacityKg: input.capacityKg.toString(), isActive: true }); return { profileId: profile.id }; }),
    setAvailability: protectedProcedure.input(z.object({ status: z.enum(["ONLINE", "OFFLINE"]) })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, "DRIVER"); const db = await getDb(); if (!db) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "قاعدة البيانات غير متاحة" }); const profile = await getDriverProfile(ctx.user.id); if (!profile) throw new TRPCError({ code: "BAD_REQUEST", message: "أكمل بيانات السائق والمركبة أولاً" }); const activeVehicle = (await db.select().from(vehicles).where(and(eq(vehicles.driverId, profile.id), eq(vehicles.isActive, true))).limit(1))[0]; if (input.status === "ONLINE" && !activeVehicle) throw new TRPCError({ code: "BAD_REQUEST", message: "أضف مركبة نشطة قبل التوفر لاستقبال الطلبات" }); await db.update(driverProfiles).set({ driverStatus: input.status }).where(eq(driverProfiles.id, profile.id)); return { status: input.status }; }),
    offers: protectedProcedure.query(async ({ ctx }) => { requireRole(ctx.user, "DRIVER"); const profile = await getDriverProfile(ctx.user.id); return profile ? listDriverOffers(profile.id) : []; }),
    trips: protectedProcedure.query(async ({ ctx }) => { requireRole(ctx.user, "DRIVER"); const profile = await getDriverProfile(ctx.user.id); return profile ? listDriverTrips(profile.id) : []; }),
    respondOffer: protectedProcedure.input(z.object({ offerId: z.number().int(), accept: z.boolean() })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, "DRIVER"); const db = await getDb(); if (!db) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "قاعدة البيانات غير متاحة" }); const profile = await getDriverProfile(ctx.user.id); if (!profile) throw new TRPCError({ code: "BAD_REQUEST", message: "ملف السائق غير مكتمل" }); const offer = (await db.select().from(driverOffers).where(and(eq(driverOffers.id, input.offerId), eq(driverOffers.driverId, profile.id), eq(driverOffers.status, "PENDING"))).limit(1))[0]; if (!offer || offer.expiresAt < new Date()) throw new TRPCError({ code: "BAD_REQUEST", message: "انتهت صلاحية العرض" }); if (!input.accept) { await db.update(driverOffers).set({ status: "REJECTED", respondedAt: new Date() }).where(eq(driverOffers.id, input.offerId)); return { accepted: false }; } const active = await db.select().from(orders).where(and(eq(orders.driverId, profile.id), sql`${orders.status} in ('DRIVER_ASSIGNED','DRIVER_GOING_TO_PICKUP','ARRIVED_AT_PICKUP','ORDER_PICKED_UP','IN_DELIVERY','ARRIVED_AT_DESTINATION')`)).limit(1); if (active.length) throw new TRPCError({ code: "CONFLICT", message: "لديك طلب نشط بالفعل" }); await db.update(driverOffers).set({ status: "ACCEPTED", respondedAt: new Date() }).where(eq(driverOffers.id, input.offerId)); await db.update(orders).set({ driverId: profile.id, status: "DRIVER_ASSIGNED" }).where(eq(orders.id, offer.orderId)); await db.update(driverProfiles).set({ driverStatus: "BUSY" }).where(eq(driverProfiles.id, profile.id)); await appendStatus(offer.orderId, "SEARCHING_DRIVER", "DRIVER_ASSIGNED", ctx.user.id, "قبل السائق العرض"); return { accepted: true, orderId: offer.orderId }; }),
    transition: protectedProcedure.input(z.object({ orderId: z.number().int(), toStatus: z.enum(orderStatusValues), note: z.string().max(500).optional() })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, "DRIVER"); const db = await getDb(); if (!db) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "قاعدة البيانات غير متاحة" }); const profile = await getDriverProfile(ctx.user.id); if (!profile) throw new TRPCError({ code: "BAD_REQUEST", message: "ملف السائق غير مكتمل" }); const order = (await db.select().from(orders).where(and(eq(orders.id, input.orderId), eq(orders.driverId, profile.id))).limit(1))[0]; if (!order || !transitionMap[order.status]?.includes(input.toStatus)) throw new TRPCError({ code: "BAD_REQUEST", message: "انتقال حالة الطلب غير مسموح" }); await db.update(orders).set({ status: input.toStatus, finalFare: input.toStatus === "DELIVERED" ? order.estimatedFare : order.finalFare, paymentStatus: input.toStatus === "DELIVERED" ? "PAID" : order.paymentStatus }).where(eq(orders.id, input.orderId)); await appendStatus(input.orderId, order.status, input.toStatus, ctx.user.id, input.note); if (input.toStatus === "DELIVERED" || input.toStatus === "COMPLETED") await db.update(driverProfiles).set({ driverStatus: "ONLINE", totalTrips: sql`${driverProfiles.totalTrips} + 1`, totalEarnings: sql`${driverProfiles.totalEarnings} + ${order.estimatedFare ?? "0"}` }).where(eq(driverProfiles.id, profile.id)); return { status: input.toStatus, statusLabel: statusLabels[input.toStatus] }; }),
  }),
  admin: router({
    stats: adminProcedure.query(() => getDashboardStats()),
    orders: adminProcedure.query(() => listAdminOrders()),
    availableDrivers: adminProcedure.input(z.object({ vehicleType: vehicleEnum.optional() }).optional()).query(async ({ input }) => { const db = await getDb(); if (!db) return []; const conditions = [eq(driverProfiles.driverStatus, "ONLINE"), eq(vehicles.isActive, true)]; if (input?.vehicleType) conditions.push(eq(vehicles.vehicleType, input.vehicleType)); return db.select({ profile: driverProfiles, vehicle: vehicles, user: users }).from(driverProfiles).innerJoin(vehicles, eq(vehicles.driverId, driverProfiles.id)).innerJoin(users, eq(users.id, driverProfiles.userId)).where(and(...conditions)).limit(50); }),
    assignDriver: adminProcedure.input(z.object({ orderId: z.number().int(), driverProfileId: z.number().int() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "قاعدة البيانات غير متاحة" }); await db.update(orders).set({ driverId: input.driverProfileId, status: "DRIVER_ASSIGNED" }).where(eq(orders.id, input.orderId)); await createAudit(ctx.user.id, "ASSIGN_DRIVER", "ORDER", input.orderId, { driverProfileId: input.driverProfileId }); await appendStatus(input.orderId, "SEARCHING_DRIVER", "DRIVER_ASSIGNED", ctx.user.id, "تعيين يدوي من المشرف"); return { success: true }; }),
    updatePricing: adminProcedure.input(z.object({ id: z.number().int(), baseFare: z.number().min(0), perKm: z.number().min(0), minimumFare: z.number().min(0), extraWeightFee: z.number().min(0) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "قاعدة البيانات غير متاحة" }); await db.update((await import("../drizzle/schema")).pricingRules).set({ baseFare: input.baseFare.toString(), perKm: input.perKm.toString(), minimumFare: input.minimumFare.toString(), extraWeightFee: input.extraWeightFee.toString() }).where(eq((await import("../drizzle/schema")).pricingRules.id, input.id)); await createAudit(ctx.user.id, "UPDATE_PRICING", "PRICING_RULE", input.id, input); return { success: true }; }),
  }),
});
export type AppRouter = typeof appRouter;
